export type AcquiredPalette = {
  background: string;
  color: string;
  accent: string;
};

export type AcquiredEpisode = {
  slug: string;
  name: string;
  mark: string;
  label: string;
  portrait?: boolean;
  season: string;
  episode: string;
  date: string;
  duration: string;
  sponsor: string;
  categories: string[];
  tagline: string;
  dek: string;
  description: string[];
  links: string[];
  carveOuts: string[];
  corrections?: string;
  palette: AcquiredPalette;
};

const commonDescription = [
  "Acquired tells the definitive history and strategy behind the world's most important companies. This replica page mirrors the dark editorial treatment, generous reading column, and premium playback surface of the Acquired episode experience.",
  "The story follows the inflection points, strategic choices, capital allocation decisions, and cultural obsessions that turned an ambitious company into an enduring institution.",
];

export const acquiredEpisodes: AcquiredEpisode[] = [
  {
    slug: "visa",
    name: "Visa",
    mark: "VISA",
    label: "Visa",
    season: "Spring 2026",
    episode: "Episode 6",
    date: "July 19, 2026",
    duration: "3h 12m",
    sponsor: "J.P. Morgan",
    categories: ["Payments", "Networks"],
    tagline: "The original internet of money.",
    dek: "How a bank-card experiment became the most valuable toll road in global commerce.",
    description: commonDescription,
    links: ["BankAmericard origins", "Network effects in payments", "Visa IPO history"],
    carveOuts: ["The Power Broker", "The Everything Store"],
    palette: { background: "#0757f9", color: "#ffffff", accent: "#9fc4ff" },
  },
  {
    slug: "charlie-munger",
    name: "Charlie Munger",
    mark: "CM",
    label: "Charlie",
    portrait: true,
    season: "Spring 2026",
    episode: "Episode 5",
    date: "July 5, 2026",
    duration: "2h 48m",
    sponsor: "J.P. Morgan",
    categories: ["Investing", "Berkshire"],
    tagline: "The operating system behind Berkshire.",
    dek: "A study of judgment, incentives, patience, and the latticework that shaped modern investing.",
    description: commonDescription,
    links: ["Poor Charlie's Almanack", "Berkshire annual letters", "Daily Journal meetings"],
    carveOuts: ["Seeking Wisdom", "Damn Right!"],
    palette: { background: "#c7b18e", color: "#142033", accent: "#f6eee0" },
  },
  {
    slug: "rolex",
    name: "Rolex",
    mark: "ROLEX",
    label: "Rolex",
    season: "Spring 2026",
    episode: "Episode 4",
    date: "June 28, 2026",
    duration: "2h 36m",
    sponsor: "J.P. Morgan",
    categories: ["Luxury", "Manufacturing"],
    tagline: "Scarcity, precision, and the crown.",
    dek: "How Rolex made reliability aspirational and built one of the world's strongest luxury brands.",
    description: commonDescription,
    links: ["Hans Wilsdorf biography", "Oyster case history", "Luxury watch market"],
    carveOuts: ["The Watch Book", "The Founder"],
    palette: { background: "#007241", color: "#f0f7db", accent: "#d8b65a" },
  },
  {
    slug: "ferrari",
    name: "Ferrari",
    mark: "F",
    label: "Ferrari",
    season: "Spring 2026",
    episode: "Episode 3",
    date: "June 8, 2026",
    duration: "3h 02m",
    sponsor: "J.P. Morgan",
    categories: ["Automotive", "Luxury"],
    tagline: "The business of desire.",
    dek: "How racing losses, disciplined scarcity, and mythmaking made Ferrari a category of one.",
    description: commonDescription,
    links: ["Enzo Ferrari history", "Formula 1 economics", "Luxury gross margins"],
    carveOuts: ["Rush", "The Art of Racing in the Rain"],
    palette: { background: "#ef1708", color: "#fff4ed", accent: "#ffd848" },
  },
  {
    slug: "mark-zuckerberg",
    name: "Mark Zuckerberg",
    mark: "MZ",
    label: "Mark Zuckerberg",
    portrait: true,
    season: "Spring 2026",
    episode: "Episode 2",
    date: "May 24, 2026",
    duration: "2h 55m",
    sponsor: "J.P. Morgan",
    categories: ["Social", "Founder"],
    tagline: "Founder control at planetary scale.",
    dek: "The story of Facebook, Meta, and the compounding effects of product instincts plus control.",
    description: commonDescription,
    links: ["The Facebook Effect", "Meta annual reports", "Instagram acquisition"],
    carveOuts: ["The Social Network", "The Innovator's Dilemma"],
    palette: { background: "#043c42", color: "#d7f3f1", accent: "#63bfbc" },
  },
  {
    slug: "microsoft",
    name: "Microsoft",
    mark: "MICROSOFT",
    label: "Microsoft I",
    season: "Spring 2026",
    episode: "Episode 1",
    date: "May 10, 2026",
    duration: "3h 20m",
    sponsor: "J.P. Morgan",
    categories: ["Software", "Platforms"],
    tagline: "A platform company learns to compound.",
    dek: "From DOS to Windows to Azure, Microsoft repeatedly found the leverage point in computing.",
    description: commonDescription,
    links: ["Hard Drive", "Microsoft annual reports", "OpenAI partnership"],
    carveOuts: ["Showstopper!", "Developers!"],
    palette: { background: "#006ccf", color: "#ecf7ff", accent: "#72b5ff" },
  },
  {
    slug: "jamie-dimon",
    name: "Jamie Dimon",
    mark: "JD",
    label: "Jamie Dimon",
    portrait: true,
    season: "Winter 2026",
    episode: "Episode 9",
    date: "April 19, 2026",
    duration: "2h 44m",
    sponsor: "J.P. Morgan",
    categories: ["Banking", "Leadership"],
    tagline: "Risk, scale, and the fortress balance sheet.",
    dek: "A career-long case study in banking through crisis, consolidation, and operating discipline.",
    description: commonDescription,
    links: ["JPMorgan annual letters", "Bank One merger", "Financial crisis timeline"],
    carveOuts: ["The Partnership", "Too Big to Fail"],
    palette: { background: "#b9c8bd", color: "#142033", accent: "#f3efe6" },
  },
  {
    slug: "the-walt-disney-company",
    name: "Disney I",
    mark: "Walt Disney",
    label: "Disney I",
    season: "Spring 2026",
    episode: "Episode 4",
    date: "June 21, 2026",
    duration: "3h 38m",
    sponsor: "J.P. Morgan",
    categories: ["Media", "Entertainment"],
    tagline: "The birth of the flywheel.",
    dek: "The Walt Disney Company is the most successful enterprise ever created for monetizing human nostalgia.",
    description: [
      "During Walt's era, Disney operated like an unhinged moonshot factory, blowing its finances on one seemingly impossible project after another: the first feature-length animated film, Fantasia, Disneyland, and the machinery of modern Imagineering.",
      "Those bets created a company where art, commerce, distribution, and parks reinforced one another. The result was the accidental invention of a flywheel that still powers global entertainment.",
    ],
    links: ["Snow White production history", "Disneyland opening broadcast", "The Disney War"],
    carveOuts: ["Walt Disney: An American Original", "Imagineering Story"],
    corrections: "No corrections yet. Send notes and source material through the contact link.",
    palette: { background: "#1a1a1a", color: "#eeeeee", accent: "#9d9d9d" },
  },
  {
    slug: "hermes",
    name: "Hermes",
    mark: "HERMES",
    label: "Hermes",
    season: "Winter 2026",
    episode: "Episode 8",
    date: "April 5, 2026",
    duration: "2h 31m",
    sponsor: "J.P. Morgan",
    categories: ["Luxury", "Craft"],
    tagline: "Craft as a moat.",
    dek: "How a saddlery workshop turned patience, training, and scarcity into a luxury machine.",
    description: commonDescription,
    links: ["Hermes annual reports", "Luxury supply constraints", "Birkin history"],
    carveOuts: ["Deluxe", "The Cartiers"],
    palette: { background: "#ff7900", color: "#1e1308", accent: "#f7efe0" },
  },
  {
    slug: "costco",
    name: "Costco",
    mark: "COSTCO",
    label: "Costco",
    season: "Winter 2026",
    episode: "Episode 7",
    date: "March 22, 2026",
    duration: "2h 40m",
    sponsor: "J.P. Morgan",
    categories: ["Retail", "Culture"],
    tagline: "The membership model with a soul.",
    dek: "Costco pairs operating austerity with unusual loyalty from employees, suppliers, and customers.",
    description: commonDescription,
    links: ["Price Club history", "Costco annual reports", "Membership economics"],
    carveOuts: ["The Warehouse", "Made in America"],
    palette: { background: "#0478d4", color: "#fff6ed", accent: "#ff4b36" },
  },
  {
    slug: "google-search",
    name: "Google Search",
    mark: "G",
    label: "Google Search",
    season: "Winter 2026",
    episode: "Episode 6",
    date: "March 8, 2026",
    duration: "3h 06m",
    sponsor: "J.P. Morgan",
    categories: ["Search", "Advertising"],
    tagline: "Organizing attention at internet scale.",
    dek: "PageRank, AdWords, and the business model that turned intent into one of history's best businesses.",
    description: commonDescription,
    links: ["The Google Story", "PageRank paper", "AdWords launch"],
    carveOuts: ["In the Plex", "How Google Works"],
    palette: { background: "#1b1b1b", color: "#ffffff", accent: "#ffcd38" },
  },
  {
    slug: "trader-joes",
    name: "Trader Joe's",
    mark: "TRADER JOE'S",
    label: "Trader Joe's",
    season: "Winter 2026",
    episode: "Episode 5",
    date: "February 22, 2026",
    duration: "2h 18m",
    sponsor: "J.P. Morgan",
    categories: ["Retail", "Brand"],
    tagline: "Private label as theater.",
    dek: "How a small-format grocer built a cult around discovery, restraint, and operational weirdness.",
    description: commonDescription,
    links: ["Joe Coulombe interviews", "Private label economics", "Retail theater"],
    carveOuts: ["The Everything Store", "Grocery"],
    palette: { background: "#e51c14", color: "#fff3ed", accent: "#ffd7b1" },
  },
  {
    slug: "formula-1",
    name: "Formula 1",
    mark: "F1",
    label: "Formula 1",
    season: "Winter 2026",
    episode: "Episode 4",
    date: "February 8, 2026",
    duration: "2h 52m",
    sponsor: "J.P. Morgan",
    categories: ["Sports", "Media"],
    tagline: "From bankrupt teams to global spectacle.",
    dek: "The business transformation that turned a paddock into one of the world's most valuable sports leagues.",
    description: commonDescription,
    links: ["Bernie Ecclestone history", "Liberty Media acquisition", "Drive to Survive"],
    carveOuts: ["Senna", "How to Build a Car"],
    palette: { background: "#181818", color: "#ff2b1f", accent: "#ece8e1" },
  },
  {
    slug: "vanguard",
    name: "Vanguard",
    mark: "Vanguard",
    label: "Vanguard",
    season: "Winter 2026",
    episode: "Episode 3",
    date: "January 25, 2026",
    duration: "2h 47m",
    sponsor: "J.P. Morgan",
    categories: ["Investing", "Indexing"],
    tagline: "The communist capitalist who saved investors a trillion dollars.",
    dek: "Jack Bogle's mutual ownership structure remade investing by putting costs under permanent pressure.",
    description: commonDescription,
    links: ["Bogleheads guide", "Common Sense on Mutual Funds", "Index fund history"],
    carveOuts: ["Enough", "The Little Book of Common Sense Investing"],
    palette: { background: "#8b2026", color: "#e9d1d3", accent: "#f2b2b6" },
  },
  {
    slug: "starbucks",
    name: "Starbucks",
    mark: "SB",
    label: "Starbucks",
    portrait: true,
    season: "Winter 2026",
    episode: "Episode 2",
    date: "January 11, 2026",
    duration: "2h 33m",
    sponsor: "J.P. Morgan",
    categories: ["Consumer", "Retail"],
    tagline: "The third place becomes a global habit.",
    dek: "Starbucks scaled an Italian coffee ritual into a daily consumer platform.",
    description: commonDescription,
    links: ["Pour Your Heart Into It", "Howard Schultz history", "Store expansion data"],
    carveOuts: ["Onward", "Shoe Dog"],
    palette: { background: "#d9ded1", color: "#173000", accent: "#00704a" },
  },
  {
    slug: "jensen-huang",
    name: "Jensen Huang",
    mark: "JH",
    label: "Jensen Huang",
    portrait: true,
    season: "Fall 2025",
    episode: "Episode 9",
    date: "December 14, 2025",
    duration: "3h 15m",
    sponsor: "J.P. Morgan",
    categories: ["Semiconductors", "AI"],
    tagline: "The accelerator era.",
    dek: "How Nvidia survived graphics cycles and found itself at the center of accelerated computing.",
    description: commonDescription,
    links: ["Nvidia history", "CUDA launch", "AI accelerator market"],
    carveOuts: ["The Nvidia Way", "Chip War"],
    palette: { background: "#203811", color: "#e1eed8", accent: "#7db852" },
  },
  {
    slug: "nfl",
    name: "NFL",
    mark: "NFL",
    label: "NFL",
    season: "Fall 2025",
    episode: "Episode 8",
    date: "November 30, 2025",
    duration: "2h 39m",
    sponsor: "J.P. Morgan",
    categories: ["Sports", "Media"],
    tagline: "America's media monopoly.",
    dek: "The NFL's genius is packaging scarcity, local identity, and national television into a compounding asset.",
    description: commonDescription,
    links: ["NFL media rights", "Pete Rozelle history", "Collective bargaining"],
    carveOuts: ["Friday Night Lights", "The League"],
    palette: { background: "#0f4877", color: "#ffffff", accent: "#f02936" },
  },
  {
    slug: "morris-chang",
    name: "Morris Chang",
    mark: "MC",
    label: "Morris Chang",
    portrait: true,
    season: "Fall 2025",
    episode: "Episode 7",
    date: "November 16, 2025",
    duration: "2h 57m",
    sponsor: "J.P. Morgan",
    categories: ["Semiconductors", "Foundry"],
    tagline: "The pure-play foundry that changed the world.",
    dek: "TSMC separated design from manufacturing and became the quiet center of the technology supply chain.",
    description: commonDescription,
    links: ["TSMC founding", "Morris Chang memoir", "Semiconductor supply chain"],
    carveOuts: ["Chip War", "The Idea Factory"],
    palette: { background: "#c4b59f", color: "#2b1e16", accent: "#f7efe0" },
  },
];

export function getAcquiredEpisode(slug: string): AcquiredEpisode | undefined {
  return acquiredEpisodes.find((episode) => episode.slug === slug);
}

export function getRelatedAcquiredEpisodes(slug: string, limit = 3): AcquiredEpisode[] {
  return acquiredEpisodes.filter((episode) => episode.slug !== slug).slice(0, limit);
}
